config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_prefix: "devise", controllers: { registrations: "registrations" }

  devise_scope :user do
    get "/login" => "devise/sessions#new", as: :login
    get "/logout" => "sessions#destroy", :as => :logout
    get "/signup" => "registrations#new", :as => :signup
    scope "my" do
      get "profile", to: "registrations#edit"
      put "profile/update", to: "registrations#update"
      get "password/edit", to: "registrations#edit_password"
      put "password/update", to: "registrations#update_password"
    end
  end

  unauthenticated do
    get "/logout" => redirect("/")
  end

  authenticate :user, ->(u) { u.super_admin? } do
    get "/delayed_job" => DelayedJobWeb, :anchor => false
    put "/delayed_job" => DelayedJobWeb, :anchor => false
    post "/delayed_job" => DelayedJobWeb, :anchor => false

    ActiveAdmin.routes(self)
    namespace :superadmin do
      root to: "users#index"
      resources :users
    end

  end

  get "pages/about"
  get "pages/contact_us"
  resources :contacts, only: [:create]

  authenticated :user do
    get "/pages" => "pages#index", as: :pages
  end

  unauthenticated do
    as :user do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_scope :user do
        post "login" => "sessions#create", as: "login"
      end

      resources :users, only: [:show, :create, :update, :destroy], constraints: { id: /.*/ }
    end
  end

  root "home#index"
end

app/views/shared/header/_nav.html.slim
.header
  nav.navbar.navbar-expand-lg.navbar-light.bg-light
    .container
      = link_to 'Wheel', root_path, class: 'navbar-brand'

      button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button" 
        span.navbar-toggler-icon

      .collapse.navbar-collapse#navbarSupportedContent
        .navbar-nav.ml-auto
          = render 'shared/header/nav_links'

app/views/shared/header/_nav_links.html.slim
ul.nav.navbar-nav
  li.nav-item
    = link_to 'Home', root_path, class: 'nav-link'
  li.nav-item
    = link_to 'About', pages_about_path, class: 'nav-link'
  li.nav-item
    = link_to 'Contact Us', pages_contact_us_path, class: 'nav-link'
  - if user_signed_in?
      = render 'shared/header/user_is_signed_in'
  - else
    li.nav-item
      = link_to 'Sign in', new_session_path(:user), class: 'nav-link'

app/views/shared/header/_nav_superadmin.html.slim
.header
  nav.navbar.navbar-expand-lg.navbar-light.bg-light
    .container
      = link_to 'Wheel', root_path, class: 'navbar-brand'

      button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button" 
        span.navbar-toggler-icon

      .collapse.navbar-collapse#navbarSupportedContent
        .navbar-nav.ml-auto
          = render 'shared/header/superadmin_nav_links'

app/views/shared/header/_superadmin_nav_links.html.slim
ul.nav.navbar-nav
  li.nav-item
    = link_to 'Users', superadmin_users_path, class: 'nav-link'
  li.nav-item
    = link_to 'Active Admin', active_admin_root_path, class: 'nav-link'
  li.nav-item
    = link_to 'DJ', '/delayed_job', "target" => '_blank', class: 'nav-link'
  - if user_signed_in?
      = render 'shared/header/user_is_signed_in'
  - else
    li.nav-item
      = link_to 'Sign in', new_session_path(:user), class: 'nav-link'

app/views/shared/header/_user_is_signed_in.html.slim
li.nav-item.dropdown
  a.nav-link.dropdown-toggle href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" 
    = current_user.name
  ul.dropdown-menu.dropdown-menu-right.font-size-sm.font-weight-bold aria-labelledby="navbarDropdown"
    - if super_admin_signed_in?
      = link_to 'Superadmin', superadmin_root_path, class: 'dropdown-item'
    li.divider
    = link_to 'My Account', profile_path, class: 'dropdown-item'
    = link_to 'Change Password', password_edit_path, class: 'dropdown-item'
    = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item'